name: Deploy Website to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to Hetzner
        run: |
          lftp -d -e "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ftp:passive-mode true;
          set ssl:verify-certificate no;

          open ftp://157.90.184.171;

          user ${{ secrets.FTP_USERNAME }} \"${{ secrets.FTP_PASSWORD }}\";

          ls;

          mirror -R ./ /public_html/ --verbose;

          bye;
          "